apiVersion: v1
kind: Secret
metadata:
  name: be-secrets
type: Opaque
data:
  MONGO_USERNAME: <base64-encoded-username>
  MONGO_PASSWORD: <base64-encoded-password>
  MONGO_CLUSTER: <base64-encoded-cluster-url>
  MONGO_DBNAME: <base64-encoded-dbname>
  ACCESS_TOKEN: <base64-encoded-access-token>
