variable "cluster_name" {}
variable "task_family" {}
variable "cpu" {}
variable "memory" {}
variable "container_name" {}
variable "image_url" {}
variable "container_cpu" {}
variable "container_memory" {}
variable "container_port" {}
variable "host_port" {}
variable "service_name" {}
variable "desired_count" {}
variable "subnets" {}
variable "security_groups" {}
