variable "region" {}
variable "cluster_name" {}
variable "task_family" {}
variable "cpu" {}
variable "memory" {}
variable "container_name" {}
variable "image" {}
variable "container_port" {}
variable "host_port" {}
variable "protocol" {}
variable "service_name" {}
variable "desired_count" {}
variable "subnet_ids" {}
variable "security_group_ids" {}
variable "assign_public_ip" {}