name: Checkov scanning
on:
  push:
    branches:
      - 'origin/terraform'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v1
        with:
          directory: terraform
          framework: terraform
          
