name: Build image and push to ECR

on:
  workflow_dispatch:

jobs:
  push-to-ecr:
    runs-on: ubuntu-22.04
    env:
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
      MONGO_DBNAME: ${{ secrets.MONGO_DBNAME }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create ECR repository if it doesn't exist
        run: |
          aws_account_id=$(aws sts get-caller-identity --query "Account" --output text)
          aws ecr describe-repositories --repository-names "lamlt-sonvt" || aws ecr create-repository --repository-name "lamlt-sonvt"

      - name: Build images
        run: |
          services=("Cart" "User" "Product" "front-end")
          for service in "${services[@]}"; do
            aws_account_id=$(aws sts get-caller-identity --query "Account" --output text)
            commit_id=$(echo "${GITHUB_SHA}" | cut -c1-7)
            image_name="${aws_account_id}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/lamlt-sonvt:${service,,}"
            
            # Navigate into each service directory
            cd "E-Commerce_Web_Application/$service" || exit 1
            
            # Create .env file in the current service directory
            echo "MONGO_USERNAME=${{ env.MONGO_USERNAME }}" > .env
            echo "MONGO_PASSWORD=${{ env.MONGO_PASSWORD }}" >> .env
            echo "MONGO_CLUSTER=${{ env.MONGO_CLUSTER }}" >> .env
            echo "MONGO_DBNAME=${{ env.MONGO_DBNAME }}" >> .env
            echo "ACCESS_TOKEN=${{ env.ACCESS_TOKEN }}" >> .env

            # Build Docker image
            docker build -t "$image_name" .

            # Go back to the root directory
            cd - || exit 1
          done

      - name: Push images
        run: |
          services=("Cart" "User" "Product" "front-end")
          for service in "${services[@]}"; do
            aws_account_id=$(aws sts get-caller-identity --query "Account" --output text)
            commit_id=$(echo "${GITHUB_SHA}" | cut -c1-7)
            image_name="${aws_account_id}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/lamlt-sonvt:${service,,}"
            
            # Push Docker image
            docker push "$image_name"
          done
